# Generated by Django 4.2.20 on 2025-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cartitem_payment_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='Cart_images/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
